package exceptiondemo;

import java.util.Scanner;

public class TestApp1 
{
	double a[] = new double[1000];
	public static void main(String[] args) 
	{
		
//		Scanner sc = new Scanner(System.in);
//		String value = "dwf43safd";
//		int no = Integer.parseInt(value);
//		System.out.println("No : " + (no+200));
//		TestApp1 t = null;
//		int i=0;
//		while(true) 
//		{
//			System.out.println("in Loop : " + (i++));
//			t = new TestApp1();
//		}
		
//		TestApp1 t = null;
//		System.out.println(t.toString());
		
		
//		String name = null;
//		System.out.println(name.length());
		
//		String name ="royal";
//		System.out.println(name.charAt(4));
		
		
//		int a[] = new int[5];
//		a[5]=10;
//		System.out.println(a[5]);
		
		
//		int no1,no2,ans;
//		System.out.println("Enter No1 : ");
//		no1=sc.nextInt();
//		System.out.println("Enter No2 : ");
//		no2=sc.nextInt();
//		ans = no1/no2;
//		System.out.println("Addition : " + ans);
	}
}
